name: movie_app
description: "Creating a Movie App like a Netflix by through APIs Services."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  carousel_slider: ^5.0.0
  lottie: ^3.1.3
  cached_network_image: ^3.4.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg


